### AUTH 27048 REGISTER

POST http://localhost:4000/operation 
content-type: application/json

{
    "name": "This is the name",
    "operation": "45/(33+4)"
}

###

POST http://localhost:4000/mathbot/create
content-type: application/json

{
    "name": "This is the name"
}
###

POST http://localhost:4000/mathbot/name
content-type: application/json

{
   
}