### AUTH 27048 REGISTER

POST http://localhost:4000/operation
content-type: application/json

{
    "id": "65e59c7fcd0f88d8fe5debf4",
    "operation": "45/(33+4)"
}

###

POST http://localhost:4000/mathbot/create
content-type: application/json

{
    "name": "This is the name l"
}
###

POST http://localhost:4000/mathbot/name
content-type: application/json

{
   
}